name: ipconfig
authors:
  - name: Anthony Rose
    handle: '@Cx01N'
    link: https://twitter.com/Cx01N_
description: |
  Lists the host's IPv4 addresses, hostname, and DNS server configuration.
  Useful for identifying network settings and gaining insight into local subnet
  and name resolution infrastructure.
software: ''
tactics: [TA0007]
techniques: [T1016, T1049]
background: false
output_extension:
needs_admin: false
opsec_safe: true
language: bof
min_language_version: ''
comments:
  - https://github.com/trustedsec/CS-Situational-Awareness-BOF
options:
  - name: Architecture
    description: Architecture of the beacon_funcs.o to generate with (x64 or x86).
    required: true
    value: x64
    strict: true
    suggested_values:
      - x64
      - x86
bof:
  x86: bof/situational_awareness/ipconfig/ipconfig.x86.o
  x64: bof/situational_awareness/ipconfig/ipconfig.x64.o
  entry_point: ''
  format_string: ''
script_path: ''
script_end: ''
